### PR TITLE
Use the --strict Flag for the yamllint pre-commit Hook

### PR DESCRIPTION
**Pull request by mcdonnnj**
#  #

## 🗣 Description ##

This PR adds the `--strict` flag to the [`yamllint` `pre-commit` hook](https://github.com/adrienverge/yamllint). This causes the hook to exit with a non-zero code if warnings are found instead of only if errors are found as described in [the documentation](https://yamllint.readthedocs.io/en/stable/configuration.html#errors-and-warnings).

## 💭 Motivation and Context ##

I noticed some warnings that only showed when errors were found, and thought we should be fixing warnings as well. Please see the following example from [cisagov/skeleton-packer](https://github.com/cisagov/skeleton-packer).

With the current configuration:

```console
$ pre-commit run yamllint --all-files
yamllint.................................................................Passed
```
With the change from this PR:

```console
$ pre-commit run yamllint --all-files
yamllint.................................................................Failed
- hook id: yamllint
- exit code: 2

src/requirements.yml
  1:1       warning  missing document start "---"  (document-start)

.bandit.yml
  14:10     warning  too few spaces before comment  (comments)
```

## 🧪 Testing ##

Automated tests pass, and I verified that this change does result in a difference in output if there are warnings.

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All new and existing tests pass.

### CODE REVIEW

**Review by hillaryj — APPROVED** [review]
🥇 

Any idea on a rough magnitude of number of warnings (or number of repos with warnings) that need to be updated to pass before merging? Or will they need to be updated after the merge of the config change?

**Review by dav3r — APPROVED** [review]
Let's poke the bear!  What could possibly go wrong?  ⚔️

**Comment by mcdonnnj** [comment]
> 
> 
> 🥇
> 
> Any idea on a rough magnitude of number of warnings (or number of repos with warnings) that need to be updated to pass before merging? Or will they need to be updated after the merge of the config change?

Besides the example with [cisagov/skeleton-packer](https://github.com/cisagov/skeleton-packer), I checked the other skeletons and found:

[cisagov/skeleton-python-library](https://github.com/cisagov/skeleton-python-library) (and [cisagov/skeleton-aws-lambda](https://github.com/cisagov/skeleton-aws-lamba)):

```console
$ pre-commit run yamllint --all-files
yamllint.................................................................Failed
- hook id: yamllint
- exit code: 2

.github/workflows/codeql-analysis.yml
  11:5      warning  comment not indented like content  (comments-indentation)
  71:8      warning  missing starting space in comment  (comments)
  ```
  
  Beyond inherited ones like that, I don't know how many individual repositories may have unfixed warnings lurking.

**Review by jsf9k — APPROVED** [review]
Bring the pain!

**Pull request merged**
