### PR TITLE
Add setuptools and wheel as pip dependencies

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description

This pull request adds `setuptools` and `wheel` as `pip` dependencies.

## 💭 Motivation and Context

`setuptools` usually comes along with `pip`, but `wheel` does not.  Using `wheel` where possible to build python extensions is more modern and more security conscious than using the old-style `setup.py` that `pip` reverts to if `wheel` is not installed.

While we're adding `wheel`, we may as well add `setuptools` for good measure.

## 🧪 Testing

All the pre-commit hooks pass.

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by hillaryj — APPROVED** [review]
🎡

**Review by felddy — APPROVED** [review]
Wheel in the sky keeps on turnin' 
I don't know where I'll be tomorrow 
Wheel in the sky keeps on turnin'

**Comment by felddy** [comment]
RELEASE THE LINEAGE KRAKEN!  
6ba6cb391a6f132b1d0e14fe7757f363 500x205x14

**Review by dav3r — APPROVED** [review]
🎡

**Comment by jsf9k** [comment]
I'll wait for @mcdonnnj's review and full buy-in before letting slip the dogs of lineage.

**Review by mcdonnnj — APPROVED** [review]
Let slip the Lineage!
rin_dogs

**Pull request merged**
