### PR TITLE
Detecting virtualenv installation successfully

### PR DESCRIPTION
**Pull request by arcsector**
# #

## 🗣 Description ##

Fixing [#243](https://github.com/cisagov/pshtt/issues/243)

## 💭 Motivation and context ##

See [#243](https://github.com/cisagov/pshtt/issues/243) for context

## 🧪 Testing ##

Tested using pyenv in WSL2 without a pyenv-virtualenv binary in immediate path, despite having it installed properly and `pyenv virtualenvs` command working fine

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by arcsector** [comment]
@mcdonnnj

**Comment by mcdonnnj** [comment]
@arcsector Please refer to the [contributing guide](https://github.com/cisagov/skeleton-generic/blob/develop/CONTRIBUTING.md#installing-the-pre-commit-hook) and ensure the pre-commit checks run successfully. Feel free to either commit the changes or rebase your existing commit to fix the issue.

**Comment by arcsector** [comment]
You guys need to bump your accepted python versions on your other repos - pre-commit's latest accepted version is 3.8: https://github.com/pre-commit/pre-commit/blob/main/setup.cfg

My pre-commit only shows this error:

```console
Validate docker-compose files........................(no files to check)Skipped
Packer Validate..........................................................Failed
- hook id: packer_validate
- exit code: 1

packer is required

Packer Format........................................(no files to check)Skipped
```

I'm not sure where you get or need this config - any info on how to resolve this would be appreciated

**Comment by mcdonnnj** [comment]
> You guys need to bump your accepted python versions on your other repos - pre-commit's latest accepted version is 3.8: https://github.com/pre-commit/pre-commit/blob/main/setup.cfg
> 
> My pre-commit only shows this error:
> 
> ```
> Validate docker-compose files........................(no files to check)Skipped
> Packer Validate..........................................................Failed
> - hook id: packer_validate
> - exit code: 1
> 
> packer is required
> 
> Packer Format........................................(no files to check)Skipped
> ```
> 
> I'm not sure where you get or need this config - any info on how to resolve this would be appreciated

The [`pre-commit` configuration only specifies `python3`](https://github.com/cisagov/skeleton-generic/blob/72503682a20fa77b887910ac6ec8556c77ce7d5e/.pre-commit-config.yaml#L2-L4) so I'm not sure what you're referencing. If you are referring to the GitHub Actions workflow for [cisagov/pshtt](https://github.com/cisagov/pshtt) then that is because Python 3.7 is the latest version of Python the package currently supports. All our other repos should generally be using Python 3.11 for the job that runs `pre-commit`.

The error you are seeing is because there are some tool binaries our `pre-commit` configuration relies upon (because of the configured hooks). Based on the error message you are missing [Packer].

[Terraform]: https://github.com/hashicorp/terraform
[Packer]: https://github.com/hashicorp/packer
[terraform-docs]: https://github.com/terraform-docs/terraform-docs
[shfmt]: https://github.com/mvdan/sh#shfmt

**Comment by jsf9k** [comment]
I'm glad to see this finally get fixed!  Thank you @arcsector!

**Review by jsf9k — APPROVED** [review]

**Review by dav3r — APPROVED** [review]
👍 👍  Thanks for your contribution here!

**Review by jasonodoom — APPROVED** [review]

**Comment by arcsector** [comment]
Thanks for the help @jsf9k - looks good to go.

**Comment by jsf9k** [comment]
> Thanks for the help @jsf9k - looks good to go.

We have a process ([cisagov/action-lineage](https://github.com/cisagov/action-lineage)) that walks through our repos and propagates upstream changes.  To avoid a constant barrage of small PRs in every repo that inherits from this one (which is most of the repos in cisagov), we tend wait until we have several pending PRs before kicking that process off.  This PR will definitely get merged the next time we kick off that process.

**Pull request merged**
