### PR TITLE
pre-commit Hook Maintenance and Update

### PR DESCRIPTION
**Pull request by mcdonnnj**
#  #

## 🗣 Description ##

This PR:
1. Updates the `repo` URLs for four hooks to be accurate and consistent.
2. Adds two new hooks from the base `pre-commit-hooks`.
3. Has the results of running `pre-commit autoupdate`.

## 💭 Motivation and Context ##

I noticed that the [prettier](https://github.com/prettier/prettier) [pre-commit hook](https://github.com/prettier/pre-commit/) that we switched to in #55 had been archived. Upon investigating, I saw that the repo handling that had changed, again, but this time to one of the `pre-commit` mirrors. Since I was already updating that hook, I thought I would audit the other hook URLs while I was making changes.

I also decided to add two new hooks and run an `autoupdate` to round out a hook maintenance PR.

## 🧪 Testing ##

Automated tests pass.

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All new and existing tests pass.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
Thanks for keeping us updated!

**Review by dav3r — APPROVED** [review]
All good! 👍 

Do we want to put the "blocked" label on this PR to hold it until we are ready for the next Kraken release?

**Review by hillaryj — APPROVED** [review]
A+!

**Comment by jsf9k** [comment]
> Do we want to put the "blocked" label on this PR to hold it until we are ready for the next Kraken release?

"Blocked" implies that another issue or pull request is blocking this one.  I suggest creating a new label ("Next Kraken"?) for this purpose.

**Comment by mcdonnnj** [comment]
> 
> 
> > Do we want to put the "blocked" label on this PR to hold it until we are ready for the next Kraken release?
> 
> "Blocked" implies that another issue or pull request is blocking this one. I suggest creating a new label ("Next Kraken"?) for this purpose.

I would honestly like some kind of "on hold" label to cover waiting for a deployment, a kraken, etc

**Comment by jsf9k** [comment]
> > > Do we want to put the "blocked" label on this PR to hold it until we are ready for the next Kraken release?
> > 
> > 
> > "Blocked" implies that another issue or pull request is blocking this one. I suggest creating a new label ("Next Kraken"?) for this purpose.
> 
> I would honestly like some kind of "on hold" label to cover waiting for a deployment, a kraken, etc

I am fine with an "On Hold" label that is distinct from "Blocked".  Probably @felddy can add a phone receiver emoji as well.

**Comment by mcdonnnj** [comment]
@jsf9k Alerted me that the URL for the `ansible-lint` hook has changed, so I have updated it in keeping with the other changes in this PR. I also ran `pre-commit autoupdate` again, and will run it on Thursday of next week before the planned merge of this PR.

**Pull request merged**
