### PR TITLE
Improve gitignore file comments and organization.

### PR DESCRIPTION
**Pull request by felddy**
#  #

## 🗣 Description ##

* Add a comment describing what the files does.
* Add sections to organize patterns.
* ~Add a pattern that developers may use to quickly ignore files private to their development environment.~

## 💭 Motivation and context ##

~I'd like to propose a pattern that we can use to quickly ignore files in our development environments.
I've found that sometimes I have the need for a scratch file, or a configuration that I'm testing locally that I don't want to end up under version control.~

~I've been using `*-mine.*`~

~This allows me to have files like `TODO-mine.md`, `docker-compose-mine.yml`, or `secrets-mine.json`  to live locally without fear of them making it into the repo.~

~A quick Google search didn't turn up any related proposals for something like this.   We could also use `*-ignoreme.*`,`*-nocommit.*`, `*-yourmom.*`~

Pros:
* Easy to use
* Short and meaningful
* Shouldn't ignore files inadvertently: e.g., `hexanitrodiphenylamine.py`

Cons:
* Could inadvertently ignore a file: e.g.,`land-mine.yml`
* Doesn't work with extension-less files : e.g., `LICENSE-mine`

Alternatives:
* I could just set this in my `~/.gitignore_global` file, and then `git config --global core.excludesFile ~/.gitignore_global`
* (I'll probably do that as well)

## 🧪 Testing ##

Works for me!

## 📷 Screenshots (if appropriate) ##

images

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
* [x] All new and existing tests pass.

### CODE REVIEW

**Review by jsf9k — CHANGES_REQUESTED** [review]
I don't like this.  It's too dangerous, since it could exclude something important.

This feels to me like a personal preference that should be handled in your local global `git` configuration.  As a result I suggest closing this PR unmerged.

"It's a no from me dog."

**Comment by felddy** [comment]
> I don't like this. It's too dangerous, since it could exclude something important.
> 
> This feels to me like a personal preference that should be handled in your local global `git` configuration. As a result I suggest closing this PR unmerged.
> 
> "It's a no from me dog."

Yes, It could exclude something important.  But that is an easy fix.  I'd rather err on the side of excluding something instead of including it.  

I'm fine with setting this in my globals if there is no value in this for anyone.
I checked that my IDEs are smart enough to honor that.  

I would like to merge the comments still since we do have people using the skeletons as their first interaction with `git`. 
 I do not want to abandon this PR entirely.

**Comment by hillaryj** [comment]
I also like the comments and would like to add them. I don't have a strong preference, but would err on the side of the convenience exclusions as a personal setting.

**Comment by jsf9k** [comment]
>...would err on the side of the convenience exclusions as a personal setting.

:point_up_2:

**Review by hillaryj — APPROVED** [review]
💬

**Review by jsf9k — APPROVED** [review]

**Review by dav3r — APPROVED** [review]
👻

**Review by mcdonnnj — APPROVED** [review]

**Pull request merged**
