### PR TITLE
Add link to how to set up a new repo with skeletons

### PR DESCRIPTION
**Pull request by hillaryj**
# 

## 🗣 Description

Adds a section in the project README.md about how to use the skeleton tool to set up a new skeletonized repository.

## 💭 Motivation and Context

This is the first place I checked on how to set up a new repo, so a link to the instructions will serve future-me and future-others well.

## 🧪 Testing

Pre-commit worked. Doc-only change otherwise.

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
👍

**Review by jsf9k — APPROVED** [review]
Great addition!

**Review by felddy — APPROVED** [review]
🎃

**Comment by hillaryj** [comment]
Wait on merging until we have more Lineage krakenage.

**Pull request merged**
