### PR TITLE
Add a job that runs diagnostics

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request adds a `diagnostics` job that runs these GitHub Actions:
- [crazy-max/ghaction-github-status](https://github.com/crazy-max/ghaction-github-status)
- [crazy-max/ghaction-dump-context](https://github.com/crazy-max/ghaction-dump-context)
- [step-security/harden-runner](https://github.com/step-security/harden-runner)

## 💭 Motivation and context ##

The GitHub Actions listed above are added in a separate `diagnostics` job.  As configured the actions should never fail, but they will print out information that may be useful in diagnosing workflow failures.

## 🧪 Testing ##

All automated tests pass.  I verified that the expected outputs appear in [the GitHub Actions log](https://github.com/cisagov/skeleton-generic/actions/runs/6026498448/job/16349578787?pr=144) (also [here](https://github.com/cisagov/skeleton-generic/actions/runs/6027704202/job/16353486732?pr=144)).

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by mcdonnnj — CHANGES_REQUESTED** [review]
Thanks for setting up this PR! I'm on board but I have two thoughts for consideration. First, would you please add this to the list of commented out dependencies in the Dependabot configuration:
https://github.com/cisagov/skeleton-generic/blob/bd762fe4c4b41eca45fe8f0e3f3fa26bbfa0345c/.github/dependabot.yml#L15-L21
Second, and this one is more a thought, what do you think about adding a `needs` block to the `lint` job and requiring the `diagnostics` job? Even if the `diagnostics` job does not currently leverage the ability for the Action to fail depending on the GitHub status, if the job has a problem while running that will generally not be a good sign for the `lint` job to run.

**Comment by jsf9k** [comment]
> Thanks for setting up this PR! I'm on board but I have two thoughts for consideration. First, would you please add this to the list of commented out dependencies in the Dependabot configuration:
> 
> https://github.com/cisagov/skeleton-generic/blob/bd762fe4c4b41eca45fe8f0e3f3fa26bbfa0345c/.github/dependabot.yml#L15-L21
> 
> 
> Second, and this one is more a thought, what do you think about adding a `needs` block to the `lint` job and requiring the `diagnostics` job? Even if the `diagnostics` job does not currently leverage the ability for the Action to fail depending on the GitHub status, if the job has a problem while running that will generally not be a good sign for the `lint` job to run.

@mcdonnnj - Please see commits 3e51119 and f88b9d2.

**Review by dav3r — APPROVED** [review]
Thanks @jsf9k (and also crazy-max) - this is a useful addition!

**Review by dav3r — APPROVED** [review]
👍 👍 👍

**Comment by mcdonnnj** [comment]
@jsf9k Would you please update the PR description to include the addition of the `step-security/harden-runner` Action?

**Comment by jsf9k** [comment]
> @jsf9k Would you please update the PR description to include the addition of the `step-security/harden-runner` Action?

I just did it while you were writing your comment.  Synchronicity!

**Comment by jsf9k** [comment]
I'm don't think that the [step-security/harden-runner](https://github.com/step-security/harden-runner) Action is covering the `lint` job when it is inserted only in the `diagnostics` job.  I think that Action may need to be duplicated in each workflow job to actually provide the desired coverage.  Am I right, @cisagov/team-ois?

I created commit 2bddec4 to test this hypothesis.

**Comment by mcdonnnj** [comment]
> I'm don't think that the [step-security/harden-runner](https://github.com/step-security/harden-runner) Action is covering the `lint` job when it is inserted only in the `diagnostics` job. I think that Action may need to be duplicated in each workflow job to actually provide the desired coverage. Am I right, @cisagov/team-ois?
> 
> I created commit [2bddec4](https://github.com/cisagov/skeleton-generic/commit/2bddec4be5bf900860323d590e4f4068c714c7c1) to test this hypothesis.

Oh, right. Each job is its own runner so it would need to be used in every job you want hardened.

**Review by dav3r — APPROVED** [review]
🤖

**Comment by jsf9k** [comment]
> I created commit [2bddec4](https://github.com/cisagov/skeleton-generic/commit/2bddec4be5bf900860323d590e4f4068c714c7c1) to test this hypothesis.

Looks like I was correct, so I'll leave the commit in place.

**Comment by mcdonnnj** [comment]
> > I created commit [2bddec4](https://github.com/cisagov/skeleton-generic/commit/2bddec4be5bf900860323d590e4f4068c714c7c1) to test this hypothesis.
> 
> Looks like I was correct, so I'll leave the commit in place.

@jsf9k Yes, please see my comment in https://github.com/cisagov/skeleton-generic/pull/144#issuecomment-1699551781. Also you may want to mention that the `step-security/harden-runner` Action must be added in every job (and that you added it to the `lint` job) in the description to better track when the kraken this change is included in is being resolved.

**Review by mcdonnnj — APPROVED** [review]
:godmode:

**Comment by jsf9k** [comment]
> Also you may want to mention that the `step-security/harden-runner` Action must be added in every job (and that you added it to the `lint` job) in the description to better track when the kraken this change is included in is being resolved.

Please see commit 69dd196.

**Review by dav3r — APPROVED** [review]
⚡

**Review by jasonodoom — APPROVED** [review]

**Pull request merged**
