### PR TITLE
Add the beautysh pre-commit hook

### PR DESCRIPTION
**Pull request by mcdonnnj**
#  #

## 🗣 Description ##

This PR adds a new [pre-commit](https://pre-commit.com) hook to our collection: [beautysh](https://github.com/lovesegfault/beautysh). It also applies the changes that hook desires to this repository.

## 💭 Motivation and Context ##

This hook performs auto-formatting of `bash` scripts. This will make our shell scripts consistently formatted across our various and scattered code bases, and do so automatically.

## 🧪 Testing ##
Automated tests pass, and you can see this hook run against one of our most script heavy projects here: https://github.com/cisagov/cyhy_amis/commit/e1500a914f7eb1a9c2e1a520a0cb03921955b4da

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All new and existing tests pass.

### CODE REVIEW

**Comment by jsf9k** [comment]
Have you tested that this won't interfere with `shellcheck`?

**Comment by mcdonnnj** [comment]
> 
> 
> Have you tested that this won't interfere with `shellcheck`?

Running the `shell-lint` hook (`shellcheck`) against the [cisagov/cyhy_amis](https://github.com/cisagov/cyhy_amis) branch I link above, the output does not appear to be affected by the formatting. This formatter is focused mainly on structure, and is not exhaustive like [black](https://github.com/psf/black) or similar auto-formatters.

I checked this by running `pre-commit run shell-lint --all-files`, and the output is below. Important to note that the `shell-lint` hook is not enabled and resolved in that repository yet, so there are quite a number of issues. It just happens to be a repository with a substantial amount of shell scripts to check against.

```console
Shell Syntax Check.......................................................Failed
- hook id: shell-lint
- exit code: 1

In terraform/scripts/non_nvme_disk_setup.sh line 20:
while [ `lsblk | grep -c " disk"` -lt ${num_disks} ]
        ^-----------------------^ SC2046: Quote this to prevent word splitting.
        ^-----------------------^ SC2006: Use $(...) notation instead of legacy backticked `...`.
                                      ^----------^ SC2154: num_disks is referenced but not assigned.
                                      ^----------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
while [ $(lsblk | grep -c " disk") -lt "${num_disks}" ]


In terraform/scripts/non_nvme_disk_setup.sh line 27:
blkid -c /dev/null ${device_name} || mkfs -t ${fs_type} -L ${label} ${device_name}
                   ^------------^ SC2154: device_name is referenced but not assigned.
                   ^------------^ SC2086: Double quote to prevent globbing and word splitting.
                                             ^--------^ SC2154: fs_type is referenced but not assigned.
                                             ^--------^ SC2086: Double quote to prevent globbing and word splitting.
                                                           ^------^ SC2154: label is referenced but not assigned.
                                                           ^------^ SC2086: Double quote to prevent globbing and word splitting.
                                                                    ^------------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
blkid -c /dev/null "${device_name}" || mkfs -t "${fs_type}" -L "${label}" "${device_name}"


In terraform/scripts/non_nvme_disk_setup.sh line 30:
uuid=$(blkid -s UUID -o value ${device_name})
                              ^------------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
uuid=$(blkid -s UUID -o value "${device_name}")


In terraform/scripts/non_nvme_disk_setup.sh line 33:
mount UUID="$uuid" -o ${mount_options} ${mount_point}
                      ^--------------^ SC2154: mount_options is referenced but not assigned.
                      ^--------------^ SC2086: Double quote to prevent globbing and word splitting.
                                       ^------------^ SC2154: mount_point is referenced but not assigned.
                                       ^------------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
mount UUID="$uuid" -o "${mount_options}" "${mount_point}"

For more information:
  https://www.shellcheck.net/wiki/SC2046 -- Quote this to prevent word splitt...
  https://www.shellcheck.net/wiki/SC2154 -- device_name is referenced but not...
  https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...

In terraform/scripts/disk_setup.sh line 20:
while [ `lsblk | grep -c " disk"` -lt ${num_disks} ]
        ^-----------------------^ SC2046: Quote this to prevent word splitting.
        ^-----------------------^ SC2006: Use $(...) notation instead of legacy backticked `...`.
                                      ^----------^ SC2154: num_disks is referenced but not assigned.
                                      ^----------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
while [ $(lsblk | grep -c " disk") -lt "${num_disks}" ]


In terraform/scripts/disk_setup.sh line 41:
  non_nvme_device_name=$(nvme id-ctrl -v $nvme_device | grep -o ${device_name})
                                         ^----------^ SC2086: Double quote to prevent globbing and word splitting.
                                                                ^------------^ SC2154: device_name is referenced but not assigned.
                                                                ^------------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
  non_nvme_device_name=$(nvme id-ctrl -v "$nvme_device" | grep -o "${device_name}")


In terraform/scripts/disk_setup.sh line 50:
    blkid -c /dev/null $nvme_device || mkfs -t ${fs_type} -L ${label} $nvme_device
                       ^----------^ SC2086: Double quote to prevent globbing and word splitting.
                                               ^--------^ SC2154: fs_type is referenced but not assigned.
                                               ^--------^ SC2086: Double quote to prevent globbing and word splitting.
                                                             ^------^ SC2154: label is referenced but not assigned.
                                                             ^------^ SC2086: Double quote to prevent globbing and word splitting.
                                                                      ^----------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
    blkid -c /dev/null "$nvme_device" || mkfs -t "${fs_type}" -L "${label}" "$nvme_device"


In terraform/scripts/disk_setup.sh line 53:
    uuid=$(blkid -s UUID -o value $nvme_device)
                                  ^----------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
    uuid=$(blkid -s UUID -o value "$nvme_device")


In terraform/scripts/disk_setup.sh line 56:
    mount UUID="$uuid" -o ${mount_options} ${mount_point}
                          ^--------------^ SC2154: mount_options is referenced but not assigned.
                          ^--------------^ SC2086: Double quote to prevent globbing and word splitting.
                                           ^------------^ SC2154: mount_point is referenced but not assigned.
                                           ^------------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
    mount UUID="$uuid" -o "${mount_options}" "${mount_point}"

For more information:
  https://www.shellcheck.net/wiki/SC2046 -- Quote this to prevent word splitt...
  https://www.shellcheck.net/wiki/SC2154 -- device_name is referenced but not...
  https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...

In terraform/scripts/toggle_prevent_destroy line 12:
  case ${opt} in
  ^-- SC2213: getopts specified -t, but it's not handled by this 'case'.


In terraform/scripts/toggle_prevent_destroy line 34:
find . -maxdepth 1 -name "*.tf" -exec $sed_script $regex {} $tmp_file \;
                                                  ^----^ SC2086: Double quote to prevent globbing and word splitting.
                                                            ^-------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
find . -maxdepth 1 -name "*.tf" -exec $sed_script "$regex" {} "$tmp_file" \;


In terraform/scripts/toggle_prevent_destroy line 37:
rm $tmp_file
   ^-------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
rm "$tmp_file"


In terraform_nessus_only/scripts/push_production_tfvars.sh line 10:
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
                               ^---------------^ SC2039: In POSIX sh, array references are undefined.


In terraform_nessus_only/scripts/push_production_tfvars.sh line 12:
aws s3 cp ${SCRIPT_DIR}/../${TFVARS_FILE} s3://${TERRAFORM_TFVARS_S3_BUCKET}/${TERRAFORM_DIR}/${TFVARS_FILE}
          ^-----------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
aws s3 cp "${SCRIPT_DIR}"/../${TFVARS_FILE} s3://${TERRAFORM_TFVARS_S3_BUCKET}/${TERRAFORM_DIR}/${TFVARS_FILE}


In terraform/scripts/fetch_production_tfvars.sh line 10:
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
                               ^---------------^ SC2039: In POSIX sh, array references are undefined.


In terraform/scripts/fetch_production_tfvars.sh line 12:
aws s3 cp s3://${TERRAFORM_TFVARS_S3_BUCKET}/${TERRAFORM_DIR}/${TFVARS_FILE} ${SCRIPT_DIR}/../${TFVARS_FILE}
                                                                             ^-----------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
aws s3 cp s3://${TERRAFORM_TFVARS_S3_BUCKET}/${TERRAFORM_DIR}/${TFVARS_FILE} "${SCRIPT_DIR}"/../${TFVARS_FILE}

For more information:
  https://www.shellcheck.net/wiki/SC2039 -- In POSIX sh, array references are...
  https://www.shellcheck.net/wiki/SC2213 -- getopts specified -t, but it's no...
  https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...

In terraform_nessus_only/scripts/fetch_production_tfvars.sh line 10:
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
                               ^---------------^ SC2039: In POSIX sh, array references are undefined.


In terraform_nessus_only/scripts/fetch_production_tfvars.sh line 12:
aws s3 cp s3://${TERRAFORM_TFVARS_S3_BUCKET}/${TERRAFORM_DIR}/${TFVARS_FILE} ${SCRIPT_DIR}/../${TFVARS_FILE}
                                                                             ^-----------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
aws s3 cp s3://${TERRAFORM_TFVARS_S3_BUCKET}/${TERRAFORM_DIR}/${TFVARS_FILE} "${SCRIPT_DIR}"/../${TFVARS_FILE}

For more information:
  https://www.shellcheck.net/wiki/SC2039 -- In POSIX sh, array references are...
  https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...

In terraform/scripts/push_production_tfvars.sh line 10:
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
                               ^---------------^ SC2039: In POSIX sh, array references are undefined.


In terraform/scripts/push_production_tfvars.sh line 12:
aws s3 cp ${SCRIPT_DIR}/../${TFVARS_FILE} s3://${TERRAFORM_TFVARS_S3_BUCKET}/${TERRAFORM_DIR}/${TFVARS_FILE}
          ^-----------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
aws s3 cp "${SCRIPT_DIR}"/../${TFVARS_FILE} s3://${TERRAFORM_TFVARS_S3_BUCKET}/${TERRAFORM_DIR}/${TFVARS_FILE}

For more information:
  https://www.shellcheck.net/wiki/SC2039 -- In POSIX sh, array references are...
  https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...
```

**Comment by jsf9k** [comment]
> > Have you tested that this won't interfere with `shellcheck`?
> 
> Running the `shell-lint` hook (`shellcheck`) against the [cisagov/cyhy_amis](https://github.com/cisagov/cyhy_amis) branch I link above, the output does not appear to be affected by the formatting. This formatter is focused mainly on structure, and is not exhaustive like [black](https://github.com/psf/black) or similar auto-formatters.

I like the idea of using this hook, but I'm slightly concerned about flip-flopping, where one hook wants a piece of code to look one way and the other wants it to look another.  Can you run
1. `pre-commit run shell-lint --all-files`
2. `pre-commit run beautysh --all-files`
3. Modify any files that `beautysh` complains about
3. `pre-commit run shell-lint --all-files`
4. `pre-commit run beautysh --all-files`
in succession against [cisagov/cool-assessment-terraform](https://github.com/cisagov/cool-assessment-terraform)?  If the only pre-commit complaints come from step 2 then I'll feel pretty confident that flip-flopping won't be an issue.

**Comment by mcdonnnj** [comment]
> 
> 
> > > Have you tested that this won't interfere with `shellcheck`?
> > 
> > 
> > Running the `shell-lint` hook (`shellcheck`) against the [cisagov/cyhy_amis](https://github.com/cisagov/cyhy_amis) branch I link above, the output does not appear to be affected by the formatting. This formatter is focused mainly on structure, and is not exhaustive like [black](https://github.com/psf/black) or similar auto-formatters.
> 
> I like the idea of using this hook, but I'm slightly concerned about flip-flopping, where one hook wants a piece of code to look one way and the other wants it to look another. Can you run
> 
>     1. `pre-commit run shell-lint --all-files`
> 
>     2. `pre-commit run beautysh --all-files`
> 
>     3. Modify any files that `beautysh` complains about
> 
>     4. `pre-commit run shell-lint --all-files`
> 
>     5. `pre-commit run beautysh --all-files`
>        in succession against [cisagov/cool-assessment-terraform](https://github.com/cisagov/cool-assessment-terraform)?  If the only pre-commit complaints come from step 2 then I'll feel pretty confident that flip-flopping won't be an issue.

```console
$ pre-commit run shell-lint --all-files
Shell Syntax Check.......................................................Passed
```

```console
$ pre-commit run beautysh --all-files
beautysh.................................................................Failed
- hook id: beautysh
- files were modified by this hook
```

`cloud-init/mount-efs-share.tpl.sh` and `setup-env` were the only files modified, and the latter is expected.

```console
$ pre-commit run shell-lint --all-files
Shell Syntax Check.......................................................Passed
```

```console
$ pre-commit run beautysh --all-files
beautysh.................................................................Passed
```

Then for completeness:

```diff
$ git diff --cached cloud-init/mount-efs-share.tpl.sh
diff --git a/cloud-init/mount-efs-share.tpl.sh b/cloud-init/mount-efs-share.tpl.sh
index b4f3b7f..7ac302d 100755
--- a/cloud-init/mount-efs-share.tpl.sh
+++ b/cloud-init/mount-efs-share.tpl.sh
@@ -10,7 +10,7 @@ set -o pipefail
 # shellcheck disable=SC2154
 until findmnt "${mount_point}"
 do
-    sleep 2
-    echo Attempting to mount EFS share at "${mount_point}".
-    mount --all
+  sleep 2
+  echo Attempting to mount EFS share at "${mount_point}".
+  mount --all
 done
```

**Review by jsf9k — APPROVED** [review]
I love it!

**Review by hillaryj — APPROVED** [review]
😻

**Pull request merged**
