### PR TITLE
Remove Trailing Quotation Mark from Actions Cache Key

### PR DESCRIPTION
**Pull request by mcdonnnj**
## 🗣 Description ##

This PR removes a trailing quotation mark from the `lint` job's `actions/cache` key. It also removes the trailing newline (`\n`) added by switching to the block scalar format (`|`).

## 💭 Motivation and Context ##

in #59 the value for the `actions/cache` key was changed to use the pipe form for block scalars, but in the process the ending quotation mark was not removed.

## 🧪 Testing ##

I confirmed that the key being used by the action no longer has a trailing quotation mark.

### Last Merged PR Run ###

https://github.com/cisagov/skeleton-generic/runs/1419430869?check_suite_focus=true#step:4:6

```console
key: lint-Linux-\
  py3.9.0-\
  4d6c2ba2786097c74dca7abc3707d576242350073cf738b69537399d20cd487c-\
  c2a90360b9139caea83bba3d7e2739e350b7e3aa53efe7922108b2b44325c3ee-\
  ac3b46e98deceeb8fd1f101d93a2b45598b68a7975471a0d63d052e0b2f20ca8"
  
restore-keys: lint-Linux-\
```

### Last `apb` Run ###

https://github.com/cisagov/skeleton-generic/runs/1381786531?check_suite_focus=true#step:5:6

```console
key: lint-Linux-py3.9.0-4d6c2ba2786097c74dca7abc3707d576242350073cf738b69537399d20cd487c-c2a90360b9139caea83bba3d7e2739e350b7e3aa53efe7922108b2b44325c3ee-9ff6996b601c7d804757a92c10ff7756d543bded97848e5705c3034c17535606
restore-keys: lint-Linux-py3.9.0
```

### Latest Run for This PR ###

https://github.com/cisagov/skeleton-generic/runs/1425159070?check_suite_focus=true#step:4:6

```console
key: lint-Linux-\
  py3.9.0-\
  4d6c2ba2786097c74dca7abc3707d576242350073cf738b69537399d20cd487c-\
  c2a90360b9139caea83bba3d7e2739e350b7e3aa53efe7922108b2b44325c3ee-\
  ac3b46e98deceeb8fd1f101d93a2b45598b68a7975471a0d63d052e0b2f20ca8
restore-keys: lint-Linux-\
```

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All new and existing tests pass.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
Good catch!
:+1:

**Review by dav3r — APPROVED** [review]
It's the little things that make life worth living. 👍

**Review by hillaryj — APPROVED** [review]
🅰️ ➕

**Review by felddy — APPROVED** [review]
Good catch!!!  This could have been our Mariner I.  🚀 💥

**Comment by mcdonnnj** [comment]
This PR is closed in favor the revamp in https://github.com/cisagov/skeleton-generic/pull/62.

**Pull request closed without merging**
