### PR TITLE
Add apostrophe to Qapla

### PR DESCRIPTION
**Pull request by jasonodoom**
## 🗣 Description ##

This pull request adds the missing apostrophe to Qapla.

## 💭 Motivation and context ##

Satisfies [a comment made in cisagov/skeleton-generic#131](https://github.com/cisagov/cool-dns-dmarc-import/pull/3#discussion_r1210512432).

## 🧪 Testing ##

All automated tests pass.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
The very pillars of heaven quake with the magnitude of this change!

**Review by mcdonnnj — APPROVED** [review]
Truly prodigious strides in quality!

**Review by dv4harr10 — APPROVED** [review]

**Review by felddy — APPROVED** [review]
Daq qo'noS vItlhutlh, vaj bIQtIqDaq jaghpu' tIqwIj. Qapla'!

**Review by dav3r — APPROVED** [review]
🤯

**Pull request merged**
