### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by hillaryj**
Adds me as a code owner now that I have onboarded!

## 🗣 Description

Add me, Hillary, @hillaryj to the code owners

## 💭 Motivation and Context

This change is required so that nobody has to remember to add me to the list of folks to review a PR and thus will save time and effort that would be better put to other, more-useful endeavors. I was motivated to type all this to be unnecessarily pedantic in the hopes that it amuses at least one person (including myself, so I have already succeeded).

## 🧪 Testing

No testing done muahaha

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
:+1:

**Review by dav3r — APPROVED** [review]
Huzzah! 🎉

**Review by mcdonnnj — APPROVED** [review]
Excellent ✨

**Review by felddy — COMMENTED** [review]
Glad you're here!  🎉

**Pull request merged**
